### PR TITLE
WIP: add maintain info and scripts

### PR DESCRIPTION
**Pull request by petrus-v**
In this PR I would like to write a scrpt to make easy to report a change made in chapter 2 to the following chapters.

I use to try different strategy, cherry pick was error prone and hard to manage over the time, history was ugly.

Then the idea is to play with rebase over next chapters branch on top of the new change introduce to a given chapter. The output will be a linear git history that makes easy readers to understand the way to build it.

This introduce the need to  ! 

I'm on the way to test this rebase strategy which will re-write the full history each time we merge a PR and will require to use **the force** in this repo (``git push -f``).
This may give some complication if we are a lot of maintainer on this repo with a lot of contribution... which is, sadely, not the case yet !

If you have a better idea, please let me know

### CODE REVIEW

**Comment by franckbret** [comment]
Hi, 

I've used the example with a team of 3 beginings dev but with some python and git background to discover Anyblok. 
My feedback is that we lost most of the time, was switching branches and understanding why the previous things did not work anymore. Not sure if it was for all steps, but I remember we rm venv and dropdb a lot, just to be sure the problem wasn't in code (at any time it was, the problem was always around installed bloks and schema migration).

Don't know if it's a big deal to do that but maybe it's simpler to maintain and manage through 1 of this 2 solutions : 

* Provide only one complete big example(the final state of the project) with everything in one branch, we lose progression but it can't fail, maintenance is easy as you only have to fix the big example when needed
* 1 branch again, but each directory in the repository is one complete project (with it's config file, and db name). This way we can avoid database collision/migration, and we keep some kind of progression. Maintenance is harder but its always easier to switch from directories than branches

**Comment by petrus-v** [comment]
Interesting, thanks for feedback.

An other solution closes to what exists is to change dbname on each chapter...

I can understand that a repo with 1 branch with a directory per chapter would be easier for readers, I'll really considering it !

**Comment by jssuzanne** [comment]
Both solutions are capable.

1) Add one branch, with a merge of all example.
2) The db name different by branch is also a good idea

**Comment by petrus-v** [comment]
I'm closing this merge request, after discussion we agreed to create only one branch with one sub-directory per chapter.

**Comment by petrus-v** [comment]
cf #6

**Pull request closed without merging**
